CREATE TABLE "AthleteProfile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "uuid" TEXT NOT NULL,
  "userId" INTEGER NOT NULL,
  "displayName" TEXT,
  "birthDate" TIMESTAMP(3),
  "gender" TEXT,
  "heightCm" DOUBLE PRECISION,
  "weightKg" DOUBLE PRECISION,
  "primarySport" TEXT,
  "trainingGoal" TEXT,
  "experienceLevel" TEXT,
  "weeklyTrainingDays" INTEGER,
  "timezone" TEXT DEFAULT 'America/Sao_Paulo',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "AthleteProfile_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "AthleteProfile_uuid_key" ON "AthleteProfile"("uuid");
CREATE UNIQUE INDEX "AthleteProfile_userId_key" ON "AthleteProfile"("userId");

ALTER TABLE "AthleteProfile"
  ADD CONSTRAINT "AthleteProfile_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
