-- Structural MVP migration: add sequential integer primary keys and keep previous cuid values as public uuid.
-- This migration attempts to preserve existing rows by copying old string ids into uuid and remapping FKs to integer ids.

ALTER TABLE "Profile" DROP CONSTRAINT IF EXISTS "Profile_userId_fkey";
ALTER TABLE "Consent" DROP CONSTRAINT IF EXISTS "Consent_userId_fkey";
ALTER TABLE "Integration" DROP CONSTRAINT IF EXISTS "Integration_userId_fkey";
ALTER TABLE "ReadinessSnapshot" DROP CONSTRAINT IF EXISTS "ReadinessSnapshot_userId_fkey";
ALTER TABLE "GarminConnection" DROP CONSTRAINT IF EXISTS "GarminConnection_userId_fkey";
ALTER TABLE "GarminSyncLog" DROP CONSTRAINT IF EXISTS "GarminSyncLog_userId_fkey";
ALTER TABLE "GarminSyncLog" DROP CONSTRAINT IF EXISTS "GarminSyncLog_connectionId_fkey";
ALTER TABLE "GarminMetric" DROP CONSTRAINT IF EXISTS "GarminMetric_userId_fkey";
ALTER TABLE "GarminMetric" DROP CONSTRAINT IF EXISTS "GarminMetric_connectionId_fkey";

DROP INDEX IF EXISTS "Profile_userId_key";
DROP INDEX IF EXISTS "Consent_userId_type_version_key";
DROP INDEX IF EXISTS "Integration_userId_provider_key";
DROP INDEX IF EXISTS "ReadinessSnapshot_userId_createdAt_idx";
DROP INDEX IF EXISTS "GarminConnection_userId_provider_key";
DROP INDEX IF EXISTS "GarminSyncLog_userId_startedAt_idx";
DROP INDEX IF EXISTS "GarminSyncLog_connectionId_startedAt_idx";
DROP INDEX IF EXISTS "GarminMetric_connectionId_type_sourceId_measuredAt_key";
DROP INDEX IF EXISTS "GarminMetric_userId_type_measuredAt_idx";
DROP INDEX IF EXISTS "GarminMetric_connectionId_measuredAt_idx";

ALTER TABLE "User" RENAME COLUMN "id" TO "uuid";
ALTER TABLE "User" DROP CONSTRAINT IF EXISTS "User_pkey";
ALTER TABLE "User" ADD COLUMN "id" INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "User" ADD CONSTRAINT "User_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX IF NOT EXISTS "User_uuid_key" ON "User"("uuid");

ALTER TABLE "Profile" RENAME COLUMN "id" TO "uuid";
ALTER TABLE "Profile" DROP CONSTRAINT IF EXISTS "Profile_pkey";
ALTER TABLE "Profile" ADD COLUMN "id" INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "Profile" ADD CONSTRAINT "Profile_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX IF NOT EXISTS "Profile_uuid_key" ON "Profile"("uuid");

ALTER TABLE "Consent" RENAME COLUMN "id" TO "uuid";
ALTER TABLE "Consent" DROP CONSTRAINT IF EXISTS "Consent_pkey";
ALTER TABLE "Consent" ADD COLUMN "id" INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "Consent" ADD CONSTRAINT "Consent_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX IF NOT EXISTS "Consent_uuid_key" ON "Consent"("uuid");
ALTER TABLE "Consent" ADD COLUMN IF NOT EXISTS "acceptedAt" TIMESTAMP(3);
ALTER TABLE "Consent" ADD COLUMN IF NOT EXISTS "ipAddress" TEXT;
ALTER TABLE "Consent" ADD COLUMN IF NOT EXISTS "userAgent" TEXT;
UPDATE "Consent" SET "acceptedAt" = COALESCE("acceptedAt", "createdAt") WHERE "accepted" = true;

ALTER TABLE "Integration" RENAME COLUMN "id" TO "uuid";
ALTER TABLE "Integration" DROP CONSTRAINT IF EXISTS "Integration_pkey";
ALTER TABLE "Integration" ADD COLUMN "id" INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "Integration" ADD CONSTRAINT "Integration_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX IF NOT EXISTS "Integration_uuid_key" ON "Integration"("uuid");

ALTER TABLE "ReadinessSnapshot" RENAME COLUMN "id" TO "uuid";
ALTER TABLE "ReadinessSnapshot" DROP CONSTRAINT IF EXISTS "ReadinessSnapshot_pkey";
ALTER TABLE "ReadinessSnapshot" ADD COLUMN "id" INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "ReadinessSnapshot" ADD CONSTRAINT "ReadinessSnapshot_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX IF NOT EXISTS "ReadinessSnapshot_uuid_key" ON "ReadinessSnapshot"("uuid");

ALTER TABLE "GarminConnection" RENAME COLUMN "id" TO "uuid";
ALTER TABLE "GarminConnection" DROP CONSTRAINT IF EXISTS "GarminConnection_pkey";
ALTER TABLE "GarminConnection" ADD COLUMN "id" INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "GarminConnection" ADD CONSTRAINT "GarminConnection_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX IF NOT EXISTS "GarminConnection_uuid_key" ON "GarminConnection"("uuid");

ALTER TABLE "GarminSyncLog" RENAME COLUMN "id" TO "uuid";
ALTER TABLE "GarminSyncLog" DROP CONSTRAINT IF EXISTS "GarminSyncLog_pkey";
ALTER TABLE "GarminSyncLog" ADD COLUMN "id" INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "GarminSyncLog" ADD CONSTRAINT "GarminSyncLog_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX IF NOT EXISTS "GarminSyncLog_uuid_key" ON "GarminSyncLog"("uuid");

ALTER TABLE "GarminMetric" RENAME COLUMN "id" TO "uuid";
ALTER TABLE "GarminMetric" DROP CONSTRAINT IF EXISTS "GarminMetric_pkey";
ALTER TABLE "GarminMetric" ADD COLUMN "id" INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "GarminMetric" ADD CONSTRAINT "GarminMetric_pkey" PRIMARY KEY ("id");
CREATE UNIQUE INDEX IF NOT EXISTS "GarminMetric_uuid_key" ON "GarminMetric"("uuid");

ALTER TABLE "Profile" ADD COLUMN "userIdInt" INTEGER;
UPDATE "Profile" p SET "userIdInt" = u."id" FROM "User" u WHERE p."userId" = u."uuid";
ALTER TABLE "Profile" DROP COLUMN "userId";
ALTER TABLE "Profile" RENAME COLUMN "userIdInt" TO "userId";
ALTER TABLE "Profile" ALTER COLUMN "userId" SET NOT NULL;

ALTER TABLE "Consent" ADD COLUMN "userIdInt" INTEGER;
UPDATE "Consent" c SET "userIdInt" = u."id" FROM "User" u WHERE c."userId" = u."uuid";
ALTER TABLE "Consent" DROP COLUMN "userId";
ALTER TABLE "Consent" RENAME COLUMN "userIdInt" TO "userId";
ALTER TABLE "Consent" ALTER COLUMN "userId" SET NOT NULL;

ALTER TABLE "Integration" ADD COLUMN "userIdInt" INTEGER;
UPDATE "Integration" i SET "userIdInt" = u."id" FROM "User" u WHERE i."userId" = u."uuid";
ALTER TABLE "Integration" DROP COLUMN "userId";
ALTER TABLE "Integration" RENAME COLUMN "userIdInt" TO "userId";
ALTER TABLE "Integration" ALTER COLUMN "userId" SET NOT NULL;

ALTER TABLE "ReadinessSnapshot" ADD COLUMN "userIdInt" INTEGER;
UPDATE "ReadinessSnapshot" r SET "userIdInt" = u."id" FROM "User" u WHERE r."userId" = u."uuid";
ALTER TABLE "ReadinessSnapshot" DROP COLUMN "userId";
ALTER TABLE "ReadinessSnapshot" RENAME COLUMN "userIdInt" TO "userId";
ALTER TABLE "ReadinessSnapshot" ALTER COLUMN "userId" SET NOT NULL;

ALTER TABLE "GarminConnection" ADD COLUMN "userIdInt" INTEGER;
UPDATE "GarminConnection" g SET "userIdInt" = u."id" FROM "User" u WHERE g."userId" = u."uuid";
ALTER TABLE "GarminConnection" DROP COLUMN "userId";
ALTER TABLE "GarminConnection" RENAME COLUMN "userIdInt" TO "userId";
ALTER TABLE "GarminConnection" ALTER COLUMN "userId" SET NOT NULL;

ALTER TABLE "GarminSyncLog" ADD COLUMN "userIdInt" INTEGER;
ALTER TABLE "GarminSyncLog" ADD COLUMN "connectionIdInt" INTEGER;
UPDATE "GarminSyncLog" l SET "userIdInt" = u."id" FROM "User" u WHERE l."userId" = u."uuid";
UPDATE "GarminSyncLog" l SET "connectionIdInt" = c."id" FROM "GarminConnection" c WHERE l."connectionId" = c."uuid";
ALTER TABLE "GarminSyncLog" DROP COLUMN "userId";
ALTER TABLE "GarminSyncLog" DROP COLUMN "connectionId";
ALTER TABLE "GarminSyncLog" RENAME COLUMN "userIdInt" TO "userId";
ALTER TABLE "GarminSyncLog" RENAME COLUMN "connectionIdInt" TO "connectionId";
ALTER TABLE "GarminSyncLog" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "GarminSyncLog" ALTER COLUMN "connectionId" SET NOT NULL;

ALTER TABLE "GarminMetric" ADD COLUMN "userIdInt" INTEGER;
ALTER TABLE "GarminMetric" ADD COLUMN "connectionIdInt" INTEGER;
UPDATE "GarminMetric" m SET "userIdInt" = u."id" FROM "User" u WHERE m."userId" = u."uuid";
UPDATE "GarminMetric" m SET "connectionIdInt" = c."id" FROM "GarminConnection" c WHERE m."connectionId" = c."uuid";
ALTER TABLE "GarminMetric" DROP COLUMN "userId";
ALTER TABLE "GarminMetric" DROP COLUMN "connectionId";
ALTER TABLE "GarminMetric" RENAME COLUMN "userIdInt" TO "userId";
ALTER TABLE "GarminMetric" RENAME COLUMN "connectionIdInt" TO "connectionId";
ALTER TABLE "GarminMetric" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "GarminMetric" ALTER COLUMN "connectionId" SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "Profile_userId_key" ON "Profile"("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "Consent_userId_type_version_key" ON "Consent"("userId", "type", "version");
CREATE UNIQUE INDEX IF NOT EXISTS "Integration_userId_provider_key" ON "Integration"("userId", "provider");
CREATE INDEX IF NOT EXISTS "ReadinessSnapshot_userId_createdAt_idx" ON "ReadinessSnapshot"("userId", "createdAt");
CREATE UNIQUE INDEX IF NOT EXISTS "GarminConnection_userId_provider_key" ON "GarminConnection"("userId", "provider");
CREATE INDEX IF NOT EXISTS "GarminConnection_status_idx" ON "GarminConnection"("status");
CREATE INDEX IF NOT EXISTS "GarminSyncLog_userId_startedAt_idx" ON "GarminSyncLog"("userId", "startedAt");
CREATE INDEX IF NOT EXISTS "GarminSyncLog_connectionId_startedAt_idx" ON "GarminSyncLog"("connectionId", "startedAt");
CREATE INDEX IF NOT EXISTS "GarminSyncLog_status_idx" ON "GarminSyncLog"("status");
CREATE UNIQUE INDEX IF NOT EXISTS "GarminMetric_connectionId_type_sourceId_measuredAt_key" ON "GarminMetric"("connectionId", "type", "sourceId", "measuredAt");
CREATE INDEX IF NOT EXISTS "GarminMetric_userId_type_measuredAt_idx" ON "GarminMetric"("userId", "type", "measuredAt");
CREATE INDEX IF NOT EXISTS "GarminMetric_connectionId_measuredAt_idx" ON "GarminMetric"("connectionId", "measuredAt");

ALTER TABLE "Profile" ADD CONSTRAINT "Profile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Consent" ADD CONSTRAINT "Consent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Integration" ADD CONSTRAINT "Integration_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ReadinessSnapshot" ADD CONSTRAINT "ReadinessSnapshot_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GarminConnection" ADD CONSTRAINT "GarminConnection_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GarminSyncLog" ADD CONSTRAINT "GarminSyncLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GarminSyncLog" ADD CONSTRAINT "GarminSyncLog_connectionId_fkey" FOREIGN KEY ("connectionId") REFERENCES "GarminConnection"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GarminMetric" ADD CONSTRAINT "GarminMetric_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GarminMetric" ADD CONSTRAINT "GarminMetric_connectionId_fkey" FOREIGN KEY ("connectionId") REFERENCES "GarminConnection"("id") ON DELETE CASCADE ON UPDATE CASCADE;
